### ISSUE TITLE
Join forces with pulsar?

### ISSUE THREAD

**Issue by mauricioszabo** [neutron-editor/neutron#1]
Hi there - unfortunately, there's no contact info on github, so I hope this doesn't sound too invasive.

Anyway, we have a group that's also trying to revive Atom from its ashes - pulsar-edit (https://github.com/pulsar-edit). We're organizing ourselves in Discord for now, if you want to join, answer me and we can discuss things there.

I am actually interested because I saw your commits to add context-aware rendering to some modules, and I think we may have some shared goals :)

**Comment by BrockWills** [comment]
Hi there,

Thanks for reaching out. I'm currently just playing around with this fork of atom, but have a decent idea of where I want to go with it, so for now I'm just going to keep working on this here.

But yes the context-aware stuff is actually pretty frustrating to be honest - just trying to get the existing Atom codebase running on latest electron has been a challenge as I'm sure you're aware. I haven't even done the context-aware stuff properly yet either, but have just done that to get a build going. I'm thinking a full rewrite of all the native modules to use NAPI is going to be my future plan.

I'll keep an eye on your project going forward though and see how it evolves - if I decide to abandon this little project at all I'd consider jumping in to help out somewhere else.

Will be interesting to see the many different forks of Atom that arise from the sunsetting. Good luck :)

**Comment by mauricioszabo** [comment]
Ok, if you want to join anyway, we have a discord channel. If you get stuck on something, or need help with something, hopefully we can work together on migrating some library so that both projects can use it.

I already started some rewrite of tree-sitter to NAPI - it was one of the libraries that was crashing the newer Electron version...

**Comment by mauricioszabo** [comment]
Just pinging you again, sorry if I'm bothering - we were able to boot the editor on Electron 19.

I'm pinging because I know you were trying to update Electron too, so I though you would be interested in this info :)
